task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox', ]

num_classes: 8 # your dataset classes +1
remap_mscoco_category: False

train_dataloader:
  type: DataLoader
  dataset:
    type: ConcatCocoDataset
    datasets: 
    - img_folder: /data/murata_phase2/thai_vehicle_yolo/images/
      ann_file: /data/murata_phase2/thai_vehicle_yolo/thai_vehicle_yolo.json
    - img_folder: /data/murata_phase2/thai_vehicle_yolo/images/
      ann_file: /data/murata_phase2/thai_vehicle_yolo/thai_vehicle_yolo.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~


  shuffle: True
  num_workers: 4
  drop_last: True
  collate_fn:
    type: BatchImageCollateFunction

val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /data/murata/kaggle_videos/SampleVideo_LowQuality_frame/images 
    ann_file: /data/murata/kaggle_videos/SampleVideo_LowQuality_frame/annotations/instances_default.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: False
  num_workers: 4
  drop_last: False
  collate_fn:
    type: BatchImageCollateFunction

coco_ids_map: ['1:car', '2:bus', '4:truck', '6:motorcycle', ] 

# coco_classes = ['person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus',
#                'train', 'truck', 'boat', 'traffic light', 'fire hydrant',
#                'stop sign', 'parking meter', 'bench', 'wild bird', 'cat', 'dog',
#                'horse', 'sheep', 'cow', 'elephant', 'bear', 'zebra', 'giraffe',
#                'backpack', 'umbrella', 'handbag/satchel', 'tie', 'luggage', 'frisbee',
#                'skating and skiing shoes', 'snowboard', 'baseball', 'kite', 'baseball bat',
#                'baseball glove', 'skateboard', 'surfboard', 'tennis racket',
#                'bottle', 'wine glass', 'cup', 'fork', 'knife', 'spoon', 'bowl/basin',
#                'banana', 'apple', 'sandwich', 'orange/tangerine', 'broccoli', 'carrot',
#                'hot dog', 'pizza', 'donut', 'cake', 'chair', 'couch',
#                'potted plant', 'bed', 'dinning table', 'toilet', 'moniter/tv', 'laptop',
#                'mouse', 'remote', 'keyboard', 'cell phone', 'microwave',
#                'oven', 'toaster', 'sink', 'refrigerator', 'book', 'clock',
#                'vase', 'scissors', 'stuffed toy', 'hair dryer', 'toothbrush']